
trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: npm ci
    displayName: Install dependencies

  - script: cp ./.npmrc-publish ~/.npmrc
    displayName: Create .npmrc

  - script: NPM_AUTH_TOKEN="$(azure-sdk-npm-token)"  npm publish --unsafe-perm
    displayName: Publish
